### ISSUE TITLE
Issue when script is not running on the same folder as the python script

### ISSUE THREAD

**Issue by andre-paulo98** [googlesamples/apk-patch-size-estimator#4]
If you aren't running the script on the same folder the script is (`python apk-size/apk_patch_size_estimator.py ...`) you get this error:
```
$ python apk-patch-size-estimator-master/apk_patch_size_estimator.py --old-file apkv/old.apk --new-file apkv/new.apk 
Error: Unable to access jarfile lib/file-by-file-tools.jar
Traceback (most recent call last):
  File "apk-patch-size-estimator-master/apk_patch_size_estimator.py", line 350, in <module>
    main()
  File "apk-patch-size-estimator-master/apk_patch_size_estimator.py", line 325, in main
    args.old_file, args.new_file, save_patch_path, temp_path)
  File "apk-patch-size-estimator-master/apk_patch_size_estimator.py", line 267, in calculate_filebyfile
    'Problem creating file by file patch, returned code: %s' % ret_code)
Exception: Problem creating file by file patch, returned code: 1
```
Most important: **Error: Unable to access jarfile lib/file-by-file-tools.jar**

**Comment by VerumCH** [comment]
Okay, better solution:

Somewhere before the code above (easiest to just do it right at the beginning), add the following:

```
dir_path = os.path.dirname(os.path.realpath(__file__))
```
then replace the `.jar` filepath argument with:
```
dir_path + '/lib/file-by-file-tools.jar'
```

This way **does not** work with hard links, but should work anywhere as long as you use a **symbolic link**. You should also have no trouble running it in the same directory as the `.py` script. There may yet be a _better_ solution, but this one should be location-agnostic and not require any changes past the initial insertion of the `dir_path` code regardless of where you move the directory afterwards. Renaming the `.jar` or removing it from the `lib/` directory would require changes, of course.

**Comment by andrewhayden** [comment]
@juliantoledo any chance of pullin in @VerumCH 's fix?

**Comment by juliantoledo** [comment]
Thank you, I just push it.

**Comment by andrewhayden** [comment]
Thanks Julian!
